print("Welcome to the Basketball Roster Program")
plr1 = input("\nWho is your point guard: ")
plr2 = input("Who is your shooting guard: ")
plr3 = input("Who is your small forward: ")
plr4 = input("Who is your power forward: ")
plr5 = input("Who is your center: ")

print("\n\tYour starting 5 for the upcoming basketball season")
print(f"\t\tPoint Guard: {plr1}\n\t\tShooting Guard: {plr2}\n\t\tSmall Forward: {plr3}\n\t\tPower Forward: {plr4}\n\t\tCenter: {plr5}")
print(f"\nOh no, {plr3} is injured.\nYour roster only has 4 players.")
plr3 = input("Who will take Lebron James's spot: ")
print("\n\tYour starting 5 for the upcoming basketball season")
print(f"\t\tPoint Guard: {plr1}\n\t\tShooting Guard: {plr2}\n\t\tSmall Forward: {plr3}\n\t\tPower Forward: {plr4}\n\t\tCenter: {plr5}")
print(f"\nGood luck {plr3} you will do great!\nYour roster now has 5 players.")